version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: airman
      POSTGRES_PASSWORD: airman
      POSTGRES_DB: airman_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
